tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    command: |
      source venv/bin/activate

vscode:
  extensions:
    - ms-python.python
    - GitHub.copilot
    - eamodio.gitlens
    - mhutchie.git-graph
    - GitHub.vscode-pull-request-github
    - ms-toolsai.jupyter
